name: Test library

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22
          - 23

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - run: npm ci

    - run: npm test
